version: '2'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Initial0
    restart: always
  rabbitmq:
    image: rabbitmq:3.6.5-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    restart: always
  etcd:
    image: quay.io/coreos/etcd:v3.0.4
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    command: /usr/local/bin/etcd -name etcd0 -cors='*' -advertise-client-urls http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 -initial-advertise-peer-urls http://127.0.0.1:2380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd -initial-cluster etcd0=http://127.0.0.1:2380 -initial-cluster-state new
    restart: always
  etcd-browser:
    image: reggiezhang/etcd-browser
    container_name: etcd-browser
    ports:
      - 8000:8000
    environment:
      - ETCD_HOST=localhost
      - AUTH_PASS=reggie
    restart: always
  redis:
    image: redis:3.2.3-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always

