version: '2'

services:
  mongo-express:
    container_name: mongo-express
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:3.4.2
    ports:
      - 27017:27017

